version: '3.1'

services:
  db:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: digital2019

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - 9000:80
    environment:
      PMA_HOST: db
